---
k3s_version: "v1.27.10+k3s2"
master_ip: "192.168.56.10"
app_namespace: "task-manager"

# Database credentials
db_user: "taskmanager"
db_password: "TaskPass123!"
db_name: "taskmanager"

# Docker images
backend_image: "taskmanager-backend:latest"
frontend_image: "taskmanager-frontend:latest"